src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Cocur\Slugify\Slugify;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\String\Slugger\SluggerInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Vich\Uploadable
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    private string $plainPassword;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private string $username;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $nickname;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $updatedAt;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $twitch;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $instagram;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $facebook;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $youtube;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $steam;

    /**
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="user")
     */
    private Collection $posts;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="user")
     */
    private Collection $comments;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable= true)
     */
    private ?string $filename;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="user_image", fileNameProperty="filename")
     */
    private ?File $imageFile = null;

    /**
     * @ORM\OneToMany(targetEntity=Video::class, mappedBy="author")
     */
    private Collection $videos;


    public function __construct()
    {
        $this->createdAt = new DateTime();
//        $this->isActive = true;
        $this->posts = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->videos = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return string
     */
    public function getPlainPassword(): string
    {
        return $this->plainPassword;
    }

    /**
     * @param string $plainPassword
     * @return User
     */
    public function setPlainPassword(string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials() :void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(?string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * @param string $username
     * @return $this
     */
    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getTwitch(): ?string
    {
        return $this->twitch;
    }

    public function setTwitch(?string $twitch): self
    {
        $this->twitch = $twitch;

        return $this;
    }

    public function getTwitter(): ?string
    {
        return $this->twitter;
    }

    public function setTwitter(?string $twitter): self
    {
        $this->twitter = $twitter;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getYoutube(): ?string
    {
        return $this->youtube;
    }

    public function setYoutube(?string $youtube): self
    {
        $this->youtube = $youtube;

        return $this;
    }

    public function getSteam(): ?string
    {
        return $this->steam;
    }

    public function setSteam(?string $steam): self
    {
        $this->steam = $steam;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getFilename(): ?string
    {
        return $this->filename;
    }

    /**
     * @param string|null $filename
     * @return User
     */
    public function setFilename(?string $filename): User
    {
        $this->filename = $filename;
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return User
     */
    public function setImageFile(?File $imageFile): User
    {
        $this->imageFile = $imageFile;

        if ($this->imageFile instanceof UploadedFile) {
            $this->updatedAt = new DateTime('now');
        }
        return $this;
    }

    public function getSlug(): ?string
    {
        $slug = (new Slugify());

        return $slug->slugify($this->getUsername());

    }

    /**
     * @return Collection|ArrayCollection
     */
    public function getPosts(): ArrayCollection|Collection
    {
        return $this->posts;
    }

    /**
     * @param Collection|ArrayCollection $posts
     * @return User
     */
    public function setPosts(ArrayCollection|Collection $posts): User
    {
        $this->posts = $posts;
        return $this;
    }

    /**
     * @return Collection|ArrayCollection
     */
    public function getComments(): ArrayCollection|Collection
    {
        return $this->comments;
    }

    /**
     * @param Collection|ArrayCollection $comments
     * @return User
     */
    public function setComments(ArrayCollection|Collection $comments): User
    {
        $this->comments = $comments;
        return $this;
    }

    public function getTitle(): string
    {
        return (string)$this->username;
    }

    /**
     * @return Collection|Video[]
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos[] = $video;
            $video->setAuthor($this);
        }

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Tag;
use App\Entity\Post;
use App\Entity\Comment;
use App\Services\Cache;
use App\Entity\Category;
use App\Form\CommentType;
use App\Repository\PostRepository;
use App\Form\CommentUserOfflineType;
use App\Controller\AbstractController;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Cache\TagAwareCacheInterface;

class BlogController extends AbstractController
{
    private PostRepository $repository;
    private EntityManagerInterface $entityManager;
    private Cache $cache;

    public function __construct(
        PostRepository $repository,
        EntityManagerInterface $entityManager,
        Cache $cache
    ) {
        $this->repository = $repository;
        $this->entityManager = $entityManager;
        $this->cache = $cache;
    }

    #[Route('/blog', name: 'blog.index')]
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $pagination = $paginator->paginate(
            $this->repository->findForBlog(),
            $request->query->getInt('page', 1),
            9
        );

        $response = $this->render('blog/index.html.twig', [
            'pagination' => $pagination
        ]);

        $response->setSharedMaxAge(600);
        return $response;
    }

    /**
     * @throws \Psr\Cache\InvalidArgumentException
     */
    #[Route('/blog/{slug}-{id}', name: 'blog.show', requirements: ['slug' => '[a-z0-9\-]*', 'id' => '[0-9\-]*'], methods: ['GET', 'POST'])]
    public function show(string $slug, Post $post, Request $request): Response
    {
        if ($post->getSlug() !== $slug) {
            return  $this->redirectToRoute(
                'blog.show',
                [
                    'id' => $post->getId(),
                    'slug' => $post->getSlug()
                ]
            );
        }
        $comment = new Comment();

        if (!$this->isGranted('IS_AUTHENTICATED_ANONYMOUSLY')) {
            $form = $this->createForm(CommentType::class, $comment);
        } else {
            $form = $this->createForm(CommentUserOfflineType::class, $comment);
        }


        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $ip = $this->get_ip_address();

            if ($this->isGranted('IS_AUTHENTICATED_FULLY')) {
                $user = $this->getUserOrThrow();
                $comment->setUser($user);
            }
            $comment->setPost($post);
            $comment->setIpAddress($ip);


            $this->entityManager->persist($comment);
            $this->entityManager->flush();

            $this->cache->invalidateTags(['comments', 'sidebar_comment', 'tagssidebar_comments_categories']);
            $this->cache->delete('comments');
            $this->cache->delete('sidebar_comment');
            $this->cache->delete('tagssidebar_comments_categories');

            return $this->redirectToRoute('blog.show', ['id' => $post->getId(), 'slug' =>  $post->getSlug()]);
        }

        $response = $this->render('blog/show.html.twig', [
            'slug' => $slug,
            'post' => $post,
            'form' => $form->createView(),
        ]);

        $response->setSharedMaxAge(600);
        return $response;
    }



    #[Route('blog/categories', name: 'categories.list')]
    public function categories(CategoryRepository $categories): Response
    {
        $response = $this->render('blog/categories.html.twig', [
            'categories' => $categories->findAll()
        ]);
        $response->setSharedMaxAge(600);
        return $response;

    }

    #[Route('blog/category/{slug}-{id<\d+>}', name: 'categories.show', requirements: ['slug' => '[a-z0-9\-]*', 'id' => '[0-9\-]*'])]
    public function category(PaginatorInterface $paginator, string $slug, int $id, Category $category, Request $request): Response
    {
        if ($category->getSlug() !== $slug) {
            return  $this->redirectToRoute(
                'categories.show',
                [
                    'slug' => $category->getSlug(),
                    'id' => $category->getId(),
                ]
            );
        }

        $pagination = $paginator->paginate(
            $this->repository->findPostByCategory((int)$category->getId()),
            $request->query->getInt('page', 1),
            9
        );
        $response = $this->render('blog/category.html.twig', [
            'category' => $category,
            'pagination' => $pagination,
            'slug' => $slug
        ]);

        $response->setSharedMaxAge(600);
        
        return $response;
    }

    #[Route('blog/tag/{slug}-{id}', name: 'tag.show', requirements: ['slug' => '[a-z0-9\-]*', 'id' => '[0-9\-]*'])]
    public function tag(PaginatorInterface $paginator, Tag $tag, string $slug, Request $request): Response
    {
        if ($tag->getSlug() !== $slug) {
            return  $this->redirectToRoute(
                'tag.show',
                [
                    'id' => $tag->getId(),
                    'slug' => $tag->getSlug()
                ]
            );
        }

        $pagination = $paginator->paginate(
            $this->repository->findPostByTag($tag->getId()),
            $request->query->getInt('page', 1),
            9
        );

        $response = $this->render('blog/tag.html.twig', [
            'tag' => $tag,
            'pagination' => $pagination
        ]);
        $response->setSharedMaxAge(600);
        
        return $response;
    }

    private function get_ip_address(): string
    {
        if (isset($_SERVER['HTTP_X_REAL_IP'])) {
            return $_SERVER['HTTP_X_REAL_IP'];
        } elseif (isset($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            // Proxy servers can send through this header like this: X-Forwarded-For: client1, proxy1, proxy2
            // Make sure we always only send through the first IP in the list which should always be the client IP.
            return (string) self::is_ip_address(trim(current(explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']))));
        } elseif (isset($_SERVER['REMOTE_ADDR'])) {
            return $_SERVER['REMOTE_ADDR'];
        }
        return '';
    }

    private static function is_ip_address(string $ip): string
    {
        return $ip;
    }
}

templates/blog/articles-card.twig
<div class="p-3 lg:w-1/4 md:w-1/2">
    <a href="{{ path('blog.show', {'slug': post.slug, 'id': post.id}) }}">
        <!--Card 1-->
        <div class="max-w-sm overflow-hidden rounded shadow-lg ">
            <img class="w-full lazyload" src="{{ vich_uploader_asset(post) | imagine_filter('blog_thumbnail') }}"
                alt="{{ post.title }}" width="384px" height="216px">
            <div class="p-4">
                <h2 class="mb-2 text-xl font-bold">{{ post.title }}</h2>
                <time class="pb-3 text-sm text-neutral-200 timeago" datetime="{{ post.createdAt| date('c')
                }}">{{ post.createdAt | format_datetime('medium', 'short', locale='fr') }}</time>
                <p class="text-base text-gray-700">
                    {{ post.content | raw | striptags| slice(0,70) }} ...
                </p>
            </div>
            {% if category is defined %}
            <div class="px-4 pt-4 pb-2">
                {% for row in array %}
                    
                {% endfor %}
                {% for tag in post.tags %}
                <span
                    class="inline-block px-3 py-1 mb-2 mr-2 text-sm font-semibold text-gray-700 bg-gray-200 rounded-full">
                    #{{ tag.name}}
                </span>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </a>
</div>

templates/blog/categories.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catégories {% endblock %}

{% block hero %}
    <div class="hero-section blog-single page-header  text-white bg-secondary">
        <div class="container">
            <h1>Catégories</h1>
        </div>
    </div>
{% endblock %}
{% block body %}
    <div class="categories-list pt-5">
        <div class="container">
            <div class="row">

                {% for category in categories %}
                    <div class="col-12 col-md-6 col-lg-3 text-center pb-5">
                        <svg class="bd-placeholder-img" width="100%"  height="320"
                             xmlns="http://www.w3.org/2000/svg" role="img"
                             aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice"
                             focusable="false"><title>{{ category.name }}</title>
                            <rect width="100%" height="100%" fill="{{ category.color }}"></rect>
                            <text x="40%" y="50%" fill="#eceeef" dy=".3em">{{ category.name }}</text>
                        </svg>

                    </div>


                {% endfor %}

            </div>
        </div>
    </div>
{% endblock %}

templates/blog/category.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category }} {% endblock %}

{% block body %}
<div class="py-5 text-white hero-section blog-single page-header bg-secondary">
    <div class="container mx-auto">
        <div class="flex flex-wrap w-full ">
            <div class="w-full mb-6 lg:w-1/2 lg:mb-0">
                <h1 class="flex items-center text-2xl font-medium text-gray-900 imb-2 sm:text-3xl title-font">
                    {{ category }}</h1>
                <div class="w-20 h-1 bg-indigo-500 rounded "></div>
            </div>
        </div>
    </div>
</div>
<div class="py-5 categories-list">
    <div class="container mx-auto">
        <div class="flex flex-wrap -m-4">
            {% cache 'catagory_page' ttl(300) %}
            {% for post in pagination %}
            {{ include('blog/articles-card.twig') }}
            {% endfor %}
            {% endcache %}
        </div>
        {{ knp_pagination_render(pagination, 'includes/pagination.html.twig') }}
    </div>
</div>
{% endblock %}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog
{% endblock %}

{% block body %}

<div class="container flex flex-wrap mx-auto">
	<div id="blog-container" class="w-full overflow-hidden md:w-3/4 lg:w-3/4 xl:w-3/4">
		<div class="container p-5 mx-auto">
			<div class="flex flex-wrap w-full mb-5">
				<div class="w-full mb-6 lg:w-1/2 lg:mb-0">
					<h1 class="mb-2 text-2xl font-medium text-gray-900 sm:text-3xl title-font">Blog</h1>
					<div class="w-20 h-1 bg-black rounded "></div>
				</div>
			</div>

			<div class="flex flex-wrap -m-4">
				{% for post in pagination %}

				<article class="p-3 lg:w-1/2 xl:w-1/3 md:w-1/2 sm:w-full">
					<div class="h-full overflow-hidden rounded-lg shadow-md ">
						<img class="object-cover object-center w-full lg:h-48 md:h-36" height="192px" width="286px"
							src="{{ vich_uploader_asset( post, 'imageFile') | imagine_filter('blog_thumbnail') }}"
							alt="{{ post.title }}" class="lazyload">
						<div class="p-6">
							<p class="text-xs font-medium tracking-widest uppercase text-slate-700 title-font">
								{{ post.category.name }}
							</p>

							<h1
								class="font-medium text-gray-600 tt-4ext-lg mmb-1 hover:text-gray-900 hover:font-semibold title-font">
								<a class=""
									href="{{ path('blog.show', {'slug': post.slug, 'id': post.id}) }}">{{ post.title}}
								</a>
							</h1>
							<time class="mb-4 text-xs border-gray-500 " datetime="{{ post.createdAt | date('c') }}">
								{{ post.createdAt | format_datetime('medium', 'short', locale='fr') }}
							</time>
							<p class="pt-2 pb-2 leading-relaxed text-md">
								{{ post.content | raw | striptags| slice(0,70) }} ...
							</p>
							<div class="flex flex-wrap items-center ">
								<a href="{{ path('blog.show', {'slug': post.slug, 'id': post.id}) }}"
									class="inline-flex items-center text-slate-700 text-md md:mb-2 lg:mb-0">
									Lire plus
								</a>
							</div>
						</div>
					</div>
				</article>

				{% endfor %}
			</div>
			{{ knp_pagination_render(pagination, 'includes/pagination.html.twig') }}
		</div>
	</div>

	<aside id="blog-sidebar" class="w-full overflow-hidden md:w-1/4 lg:w-1/4 xl:w-1/4">
		<div class="container p-5 mx-auto">
			{{ sidebar() }}
		</div>
	</aside>
</div>
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{# {{ encore_entry_script_tags('js/homepage') }} #}
{% endblock javascripts %}

templates/blog/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.title}} - Blog{% endblock %}

{% block body %}
<article>
    <header class="blog-header text-shadow-md"
        style='background-image: url({{ vich_uploader_asset(post) |  imagine_filter('blog_show')  }})'>
        <div class="overlay"> </div>
        <div class="container relative mx-auto">
            <div class="flex-grow">
                <h1 class="pb-3 text-3xl font-black sm:text-5xl">{{ post.title }}</h1>
                <ul class="items-center pt-5 xl:flex sm:inline-flex ">
                    <li class="flex items-center">
                        <time class="flex items-center pr-1 timeago"
                            datetime="{{ post.createdAt | date('c') }}">{{ icon('calendar-with-spring-binder-and-date-blocks', '18','fill-white mr-2') }}
                            {{ post.createdAt | format_datetime('full', 'short', locale='fr') | capitalize}}
                        </time>
                        <span class="pl-1 pr-1 sm:hidden lg:inline-block"> &middot; </span>
                    </li>
                    <li class="flex items-center">
                        <a class="flex items-center pr-1 lg:pl-1 hover:text-white/60"
                            href="{{ path('categories.show',{slug: post.category.slug, id: post.category.id }) }}">
                            {{ icon('category', '18','fill-white mr-2') }} {{ post.category.name }}
                        </a>
                        <span class="pl-1 pr-1 md:hidden lg:inline-block"> &middot; </span>
                    </li>
                    <li class="flex items-center">
                        <a class="flex items-center pr-1 lg:pl-1 hover:text-white/60 text-capitalize"
                            href="#author">{{ icon('profile-user', '18','fill-white mr-2') }}
                            {{ post.user.nickname | capitalize }}
                        </a>
                        <span class="pl-1 pr-1 sm:hidden lg:inline-block"> &middot; </span>
                    </li>
                    <li class="flex items-center">
                        {{ icon('message2', '18','fill-white ') }}
                        <a href="#disqus_thread" class="pl-2">
                            0 commentaire
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </header>
    <div class="blog-content">
        <div class="container mx-auto">
            {{ post.content | raw }}
        </div>
    </div>
    <section class="py-5 blog-tags">
        <div class="container mx-auto ">
            <div class="mx-5">
                <span class="inline-block font-black">Tags :</span>
                {% for tag in post.tags %}
                <span
                    class="inline-block px-3 py-1 mb-2 mr-2 text-xs font-semibold text-gray-700 uppercase bg-gray-200 rounded-lg">
                    <a class="btn btn-dark btn-sm" href="{{ path('tag.show', {id: tag.id, slug: tag.slug }) }}">
                        {{ tag.name }}
                    </a>
                </span>
            </div>
            {% endfor %}
        </div>
    </section>
    {{ include('includes/share.html.twig') }}
    {{ include('includes/author.html.twig') }}
    {{ include('includes/disqus.html.twig') }}
</article>

{% endblock %}

{% block javascripts %}
{{ parent() }}
{{ encore_entry_script_tags('js/share') }}
<script id="dsq-count-scr" src="//nest-gaming.disqus.com/count.js" async></script>
{% endblock javascripts %}

templates/blog/tag.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tag: {{ tag.name }} {% endblock %}

{% block body %}
<div class="text-white hero-section blog-single page-header bg-secondary">
    <div class="container">
        <h1>{{ tag.name }}</h1>
    </div>
</div>

<div class="py-5 text-white hero-section blog-single page-header bg-secondary">
    <div class="container mx-auto">
        <div class="flex flex-wrap w-full ">
            <div class="w-full mb-6 lg:w-1/2 lg:mb-0">
                <h1 class="flex items-center text-2xl font-medium text-gray-900 imb-2 sm:text-3xl title-font">
                    {{ tag.name }}</h1>
                <div class="w-20 h-1 bg-indigo-500 rounded "></div>
            </div>
        </div>
    </div>
</div>
<div class="py-5 tags-list">
    <div class="container mx-auto">
        <div class="flex flex-wrap -m-4">
        {% cache  "tag_page" ttl(300) %}
            {% for post in pagination %}
            {{ include('blog/articles-card.twig') }}
            {% endfor %}
        {% endcache %}

        </div>
        {{ knp_pagination_render(pagination, 'includes/pagination.html.twig') }}

    </div>
</div>
{% endblock %}